#pragma once
#define TANK_BBOX_WIDTH				26	
#define TANK_BBOX_HEIGHT			18

#define INTERRUPT_BBOX_WIDTH 22
#define INTERRUPT_BBOX_HEIGHT 18
#define INTERRUPT_BBOX_HEIGHT_ACTION 15

#define JASON_BIG_BBOX_WIDTH  26	
#define JASON_BIG_BBOX_HEIGHT 18
#define JASON_SMALL_BBOX_WIDTH	8
#define JASON_SMALL_BBOX_HEIGHT 16
